version: '3'

services:
  zk1:
    image: zookeeper:3.4.9
    hostname: zk1
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zk2:2889:3889 server.3=zk3:2890:3890
  zk2:
    image: zookeeper:3.4.9
    hostname: zk2
    ports:
      - "2182:2182"
      - "2889:2889"
      - "3889:3889"
    environment:
        ZOO_MY_ID: 2
        ZOO_PORT: 2182
        ZOO_SERVERS: server.1=zk1:2888:3888 server.2=0.0.0.0:2889:3889 server.3=zk3:2890:3890
  zk3:
    image: zookeeper:3.4.9
    hostname: zk3
    ports:
      - "2183:2183"
      - "2890:2890"
      - "3890:3890"
    environment:
        ZOO_MY_ID: 3
        ZOO_PORT: 2183
        ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2889:3889 server.3=0.0.0.0:2890:3890
  web:
      image: elkozmon/zoonavigator-web:0.5.0
      container_name: zoonavigator-web
      ports:
      - "8000:8000"
      environment:
        WEB_HTTP_PORT: 8000
        API_HOST: "api"
        API_PORT: 9000
      depends_on:
      - api
      restart: always
  api:
    image: elkozmon/zoonavigator-api:0.5.0
    container_name: zoonavigator-api
    environment:
      API_HTTP_PORT: 9000
    restart: always
  
  rabbitmq1:
    image: rabbitmq:3.7-management
    hostname: rabbitmq1
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=12345
    volumes:
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config

  rabbitmq2:
    image: rabbitmq:3.7-management
    hostname: rabbitmq2
    ports:
      - "5673:5672"
      - "15673:15672"
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=12345
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    entrypoint: /usr/local/bin/cluster-entrypoint.sh

  rabbitmq3:
    image: rabbitmq:3.7-management
    hostname: rabbitmq3
    ports:
      - "5674:5672"
      - "15674:15672"
    depends_on:
      - rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=12345
    volumes:
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
  app:
    image: rebalanser-zk-tester-rmq-app:latest
    hostname: app
    depends_on:
      - rabbitmq3
      - zk3
    environment:
      - Tester.RabbitMQ.Mode=consume
      - Tester.RabbitMQ.Group=group
      - Tester.RabbitMQ.OutQueue=output-seq
      - Tester.RabbitMQ.ZooKeeperHosts=zk1:2181,zk2:2182,zk3:2183
      - Tester.RabbitMQ.RabbitMQHost=rabbitmq1
